remove uki sha dependency
source uki using oras and remove uki repo configuration

diff --git a/features/_usi/initrd.include/usr/bin/persist b/features/_usi/initrd.include/usr/bin/persist
--- a/features/_usi/initrd.include/usr/bin/persist
+++ b/features/_usi/initrd.include/usr/bin/persist
@@ -56,15 +56,24 @@ echo "CMDLINE_LINUX=\"\$CMDLINE_LINUX hugepagesz=2MB hugepages=$hugepages\"" > /
 
 mkdir -p "$esp_dir/EFI/Linux"
 
-# where do we get the uki from?
-# using oras to download is also really hackish, temporary for CC
-# should be provided via ignition
-if ! [[ -f /sysroot/opt/persist/uki ]]; then
-	echo "no uki resource provided, exiting"
-	exit 1
+OS_RELEASE_FILE="/sysroot/etc/os-release"
+if [ ! -f "$OS_RELEASE_FILE" ]; then
+  echo "File not found '$OS_RELEASE_FILE', exiting"
+  exit 1
 fi
-export HOME=/root
-oras blob fetch "$(< /sysroot/opt/persist/uki)" -o /sysroot/efi/EFI/Linux/uki.efi
+
+# source optional config file
+[ -f /sysroot/opt/persist/gl-oci.conf ] && . /sysroot/opt/persist/gl-oci.conf
+OCI_REPO="${OCI_REPO:-keppel.global.cloud.sap/ccloud-ghcr-io-mirror/gardenlinux/gardenlinux-ccloud}"
+OCI_ARCH="${OCI_ARCH:-amd64}"
+
+# source os-release file
+. "$OS_RELEASE_FILE"
+
+# setup OCI_TAG, UKI_SHA and fetch UKI
+OCI_TAG="$GARDENLINUX_VERSION-$GARDENLINUX_CNAME-$GARDENLINUX_COMMIT_ID-$OCI_ARCH"
+UKI_SHA=$(oras manifest fetch "$OCI_REPO:${OCI_TAG}" | jq -r '.layers[] | select(.mediaType=="application/io.gardenlinux.uki") | .digest')
+oras blob fetch "$OCI_REPO@$UKI_SHA" -o "$esp_dir/EFI/Linux/uki.efi"
 
 # update the kernel cmdline in the uki
 # TODO: when using the USI tool to perform the in place update, should the cmdline of the new image also be changed?
